<a href="https://colab.research.google.com/github/2303A52393/generative-ai/blob/main/gen_ai(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error


In [2]:
y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

In [3]:
n = len(y_actual)

In [4]:
mae_manual = np.sum(np.abs(y_actual - y_pred)) / n

In [5]:
mse_manual = np.sum((y_actual - y_pred)**2) / n


In [6]:
rmse_manual = np.sqrt(mse_manual)

In [7]:
mape_manual = np.sum(np.abs((y_actual - y_pred) / y_actual)) * 100 / n


In [8]:
mae_sklearn = mean_absolute_error(y_actual, y_pred)
mse_sklearn = mean_squared_error(y_actual, y_pred)
rmse_sklearn = np.sqrt(mse_sklearn)


In [9]:
print("Manual Computations:")
print(f"MAE: {mae_manual}")
print(f"MSE: {mse_manual}")
print(f"RMSE: {rmse_manual}")
print(f"MAPE: {mape_manual}%")

Manual Computations:
MAE: 0.4600000000000016
MSE: 0.24600000000000147
RMSE: 0.49598387070549127
MAPE: 1.2733333333333368%


In [10]:
print("\nUsing sklearn:")
print(f"MAE: {mae_sklearn}")
print(f"MSE: {mse_sklearn}")
print(f"RMSE: {rmse_sklearn}")


Using sklearn:
MAE: 0.4600000000000016
MSE: 0.24600000000000147
RMSE: 0.49598387070549127


In [11]:
import numpy as np

y_actual = np.array([0, 0, 0, 0, 0, 1, 1, 1, 2, 2])
y_pred = np.array([0, 0, 1, 2, 2, 1, 2, 2, 1, 2])

def calculate_metrics(y_actual, y_pred):
    unique_classes = np.unique(np.concatenate((y_actual, y_pred)))
    confusion_matrix = np.zeros((len(unique_classes), len(unique_classes)), dtype=int)

    for actual, pred in zip(y_actual, y_pred):
        confusion_matrix[actual, pred] += 1

    accuracy = np.trace(confusion_matrix) / np.sum(confusion_matrix)
    precision = []
    recall = []

    for i in range(len(unique_classes)):
        tp = confusion_matrix[i, i]
        fp = np.sum(confusion_matrix[:, i]) - tp
        fn = np.sum(confusion_matrix[i, :]) - tp
        precision.append(tp / (tp + fp) if (tp + fp) > 0 else 0)
        recall.append(tp / (tp + fn) if (tp + fn) > 0 else 0)

    return accuracy, np.mean(precision), np.mean(recall), confusion_matrix

accuracy, precision, recall, confusion_matrix = calculate_metrics(y_actual, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(confusion_matrix)

Accuracy: 0.40
Precision: 0.51
Recall: 0.41
Confusion Matrix:
[[2 1 2]
 [0 1 2]
 [0 1 1]]
